### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by BuilderDan** [Shadows-of-Fire/Attained-Drops-2#12]
Mod doesn't appear to work with this mod when right-clicking crops to harvest:
https://minecraft.curseforge.com/projects/reap-mod?gameCategorySlug=mc-mods&projectID=244256

Its impossible to place seeds within the farming station in EnderIO:
https://minecraft.curseforge.com/projects/ender-io?gameCategorySlug=mc-mods&projectID=64578

It is also impossible to use bonemeal, perhaps adding a special bonemeal that is harder to obtain to balance out using the crops would work better than normal bonemeal.

Forge: 1.12.2-forge1.12.2-14.23.3.2675
Mod: Attained+Drops-1.12.2-3.7.3

**Comment by Shadows-of-Fire** [comment]
1) Right click harvesting is a configuration option.  Other mods will not be able to provide this functionality since Attained Drops are not "normal" plants by minecraft's standards.
2) Probably will remain that way, as Attained does not follow "normal" plant rules.  
3) No bonemeal is intended.  It will remain that way.
